import { EnemyChar, EnemyType, TargetingStrategy, TowerType, TrajectoryType } from "./enums";
import { EnemyBluePrint, ProjectileBluePrint, TowerBluePrint } from "./types";

export const DRAW_FUTURE_GIZMO = false;
// export const DRAW_FUTURE_GIZMO = true;

export const COLORS = {
    bg: 0x333355,
    desert: 0xdd6600,
    concrete: 0xacacac,
    blue: 0x3484d4,
    red: 0xd43434,
    orange: 0xd47f34,
    green: 0x34d4af,
    purple: 0xb834d4,
} as const;

export const ENEMY_BLUEPRINTS: { [k in EnemyType]: EnemyBluePrint } = {
    spider: {
        name: EnemyType.Spider,
        reward: 5,
        modelURL: "/assets/glb/spider.glb",
        speed: 3.5,
        maxHp: 40,
        modelScale: 80,
        walkAnimationName: "Wolf Spider Armature|Spider running",
    },
    orc: {
        name: EnemyType.Orc,
        reward: 10,
        // modelURL: "/assets/glb/hand-painted_orc.glb",
        modelURL: "/assets/glb/low-poly_orc.glb",
        speed: 2,
        maxHp: 200,
        modelScale: 1.5,
        walkAnimationName: "ANM_WALK",
    },
    raptor: {
        name: EnemyType.Raptor,
        reward: 10,
        modelURL: "/assets/glb/raptoid.glb",
        speed: 6,
        maxHp: 100,
        modelScale: 0.02,
        walkAnimationName: "Running",
    },
    soldier: {
        name: EnemyType.Soldier,
        reward: 15,
        modelURL: "/assets/glb/Character_Soldier.gltf",
        speed: 2,
        maxHp: 150,
        modelScale: 1.5,
        walkAnimationName: "Walk",
    },
    brigand: {
        name: EnemyType.Brigand,
        reward: 15,
        modelURL: "/assets/glb/Character_Hazmat.gltf",
        speed: 2,
        maxHp: 150,
        modelScale: 1.5,
        walkAnimationName: "Walk",
    },
    warrior: {
        name: EnemyType.Warrior,
        reward: 15,
        modelURL: "/assets/glb/Character_Enemy.gltf",
        speed: 1.6,
        maxHp: 150,
        modelScale: 1.5,
        walkAnimationName: "Walk",
    },
} as const;

export const TOWER_BLUEPRINTS: { [k in TowerType]: TowerBluePrint[] } = {
    Archer: [
        {
            name: TowerType.Archer,
            level: 1,
            defaultStrategy: TargetingStrategy.FirstInLine,
            firePointY: 6,
            damage: [4, 7],
            fireRate: 6,
            color: "blue",
            price: 100,
            range: 8,
        },
        {
            name: TowerType.Archer,
            defaultStrategy: TargetingStrategy.FirstInLine,
            firePointY: 6,
            level: 2,
            damage: [8, 13],
            fireRate: 6,
            color: "blue",
            price: 160,
            range: 9,
        },
        {
            name: TowerType.Archer,
            defaultStrategy: TargetingStrategy.FirstInLine,
            firePointY: 6,
            level: 3,
            damage: [14, 22],
            fireRate: 7,
            color: "blue",
            price: 220,
            range: 10,
        },
        {
            name: TowerType.Archer,
            defaultStrategy: TargetingStrategy.FirstInLine,
            firePointY: 6,
            level: 4,
            damage: [20, 34],
            fireRate: 8,
            color: "blue",
            price: 380,
            range: 10,
            skills: [],
        },
    ],
    Ballista: [
        {
            name: TowerType.Ballista,
            defaultStrategy: TargetingStrategy.LastInLine,
            firePointY: 8,
            level: 1,
            damage: [10, 20],
            fireRate: 2,
            color: "red",
            price: 100,
            range: 8,
        },
        {
            name: TowerType.Ballista,
            defaultStrategy: TargetingStrategy.LastInLine,
            firePointY: 8,
            level: 2,
            damage: [20, 38],
            fireRate: 2.25,
            color: "red",
            price: 160,
            range: 9,
        },
        {
            name: TowerType.Ballista,
            defaultStrategy: TargetingStrategy.LastInLine,
            firePointY: 8,
            level: 3,
            damage: [34, 55],
            fireRate: 2.5,
            color: "red",
            price: 220,
            range: 10,
        },
        {
            name: TowerType.Ballista,
            defaultStrategy: TargetingStrategy.LastInLine,
            firePointY: 8,
            level: 4,
            damage: [51, 76],
            fireRate: 2.75,
            color: "red",
            price: 380,
            range: 10,
            skills: [],
        },
    ],
    Cannon: [
        {
            name: TowerType.Cannon,
            defaultStrategy: TargetingStrategy.LastInLine,
            firePointY: 8,
            level: 1,
            damage: [18, 36],
            fireRate: 0.8,
            color: "orange",
            price: 100,
            range: 9,
        },
        {
            name: TowerType.Cannon,
            defaultStrategy: TargetingStrategy.LastInLine,
            firePointY: 8,
            level: 2,
            damage: [29, 54],
            fireRate: 0.8,
            color: "orange",
            price: 160,
            range: 10,
        },
        {
            name: TowerType.Cannon,
            defaultStrategy: TargetingStrategy.LastInLine,
            firePointY: 8,
            level: 3,
            damage: [48, 86],
            fireRate: 0.8,
            color: "orange",
            price: 220,
            range: 11,
        },
        {
            name: TowerType.Ballista,
            defaultStrategy: TargetingStrategy.LastInLine,
            firePointY: 8,
            level: 4,
            damage: [60, 100],
            fireRate: 0.8,
            color: "orange",
            price: 380,
            range: 12,
            skills: [],
        },
    ],
    Wizard: [
        {
            name: TowerType.Wizard,
            defaultStrategy: TargetingStrategy.FirstInLine,
            firePointY: 12,
            level: 1,
            damage: [10, 21],
            fireRate: 2,
            color: "purple",
            price: 100,
            range: 12,
        },
        {
            name: TowerType.Wizard,
            defaultStrategy: TargetingStrategy.FirstInLine,
            firePointY: 12,
            level: 2,
            damage: [18, 36],
            fireRate: 1.8,
            color: "purple",
            price: 160,
            range: 13,
        },
        {
            name: TowerType.Wizard,
            defaultStrategy: TargetingStrategy.FirstInLine,
            firePointY: 12,
            level: 3,
            damage: [33, 57],
            fireRate: 1.6,
            color: "purple",
            price: 220,
            range: 14,
        },
        {
            name: TowerType.Wizard,
            defaultStrategy: TargetingStrategy.FirstInLine,
            firePointY: 12,
            level: 4,
            damage: [49, 75],
            fireRate: 1.5,
            color: "purple",
            price: 380,
            range: 14,
            skills: [],
        },
    ],
    Poison: [
        {
            name: TowerType.Poison,
            defaultStrategy: TargetingStrategy.FirstInLine,
            firePointY: 8,
            level: 1,
            damage: [4, 7],
            fireRate: 3,
            color: "green",
            price: 100,
            range: 10,
        },
        {
            name: TowerType.Poison,
            defaultStrategy: TargetingStrategy.FirstInLine,
            firePointY: 8,
            level: 2,
            damage: [11, 22],
            fireRate: 2.5,
            color: "green",
            price: 160,
            range: 12,
        },
        {
            name: TowerType.Poison,
            defaultStrategy: TargetingStrategy.FirstInLine,
            firePointY: 8,
            level: 3,
            damage: [21, 37],
            fireRate: 2,
            color: "green",
            price: 220,
            range: 13,
        },
        {
            name: TowerType.Poison,
            defaultStrategy: TargetingStrategy.FirstInLine,
            firePointY: 8,
            level: 4,
            damage: [33, 60],
            fireRate: 2,
            color: "green",
            price: 380,
            range: 14,
            skills: [],
        },
    ],
};

export const PROJECTILE_BLUEPRINTS: { [k in TowerType]: ProjectileBluePrint[] } = {
    Archer: [
        {
            type: TowerType.Archer,
            level: 1,
            explosionIntensity: 0.5,
            color: "blue",
            modelScale: 0.005,
            speed: 14,
            trajectoryType: TrajectoryType.Straight,
        },
        {
            type: TowerType.Archer,
            level: 2,
            explosionIntensity: 0.5,
            color: "blue",
            modelScale: 0.005,
            speed: 14,
            trajectoryType: TrajectoryType.Straight,
        },
        {
            type: TowerType.Archer,
            level: 3,
            explosionIntensity: 0.5,
            color: "blue",
            modelScale: 0.005,
            speed: 14,
            trajectoryType: TrajectoryType.Straight,
        },
        {
            type: TowerType.Archer,
            level: 4,
            explosionIntensity: 0.5,
            color: "blue",
            modelScale: 0.005,
            speed: 14,
            trajectoryType: TrajectoryType.Straight,
        },
    ],
    Ballista: [
        {
            type: TowerType.Ballista,
            level: 1,
            explosionIntensity: 0.5,
            color: "red",
            modelScale: 0.0075,
            speed: 18,
            trajectoryType: TrajectoryType.Straight,
        },
        {
            type: TowerType.Ballista,
            level: 2,
            explosionIntensity: 0.5,
            color: "red",
            modelScale: 0.0075,
            speed: 18,
            trajectoryType: TrajectoryType.Straight,
        },
        {
            type: TowerType.Ballista,
            level: 3,
            explosionIntensity: 0.5,
            color: "red",
            modelScale: 0.0075,
            speed: 18,
            trajectoryType: TrajectoryType.Straight,
        },
        {
            type: TowerType.Ballista,
            level: 4,
            explosionIntensity: 0.5,
            color: "red",
            modelScale: 0.0075,
            speed: 18,
            trajectoryType: TrajectoryType.Straight,
        },
    ],
    Cannon: [
        {
            type: TowerType.Ballista,
            level: 1,
            explosionIntensity: 2,
            color: "orange",
            modelScale: 0.008,
            speed: 12,
            trajectoryType: TrajectoryType.Parabola,
        },
        {
            type: TowerType.Ballista,
            level: 2,
            explosionIntensity: 2,
            color: "orange",
            modelScale: 0.01,
            speed: 12,
            trajectoryType: TrajectoryType.Parabola,
        },
        {
            type: TowerType.Ballista,
            level: 3,
            explosionIntensity: 2,
            color: "orange",
            modelScale: 0.012,
            speed: 12,
            trajectoryType: TrajectoryType.Parabola,
        },
        {
            type: TowerType.Ballista,
            level: 4,
            explosionIntensity: 2,
            color: "orange",
            modelScale: 0.015,
            speed: 12,
            trajectoryType: TrajectoryType.Parabola,
        },
    ],
    Wizard: [
        {
            type: TowerType.Ballista,
            level: 1,
            explosionIntensity: 1,
            color: "purple",
            modelScale: 0.005,
            speed: 18,
            trajectoryType: TrajectoryType.Straight,
        },
        {
            type: TowerType.Ballista,
            level: 2,
            explosionIntensity: 1,
            color: "purple",
            modelScale: 0.006,
            speed: 18,
            trajectoryType: TrajectoryType.Straight,
        },
        {
            type: TowerType.Ballista,
            level: 3,
            explosionIntensity: 1,
            color: "purple",
            modelScale: 0.007,
            speed: 18,
            trajectoryType: TrajectoryType.Straight,
        },
        {
            type: TowerType.Ballista,
            level: 4,
            explosionIntensity: 1,
            color: "purple",
            modelScale: 0.008,
            speed: 18,
            trajectoryType: TrajectoryType.Straight,
        },
    ],
    Poison: [
        {
            type: TowerType.Poison,
            level: 1,
            explosionIntensity: 1,
            color: "green",
            modelScale: 0.005,
            speed: 15,
            trajectoryType: TrajectoryType.Parabola,
        },
        {
            type: TowerType.Poison,
            level: 2,
            explosionIntensity: 1,
            color: "green",
            modelScale: 0.006,
            speed: 15,
            trajectoryType: TrajectoryType.Parabola,
        },
        {
            type: TowerType.Poison,
            level: 3,
            explosionIntensity: 1,
            color: "green",
            modelScale: 0.007,
            speed: 15,
            trajectoryType: TrajectoryType.Parabola,
        },
        {
            type: TowerType.Poison,
            level: 4,
            explosionIntensity: 1,
            color: "green",
            modelScale: 0.008,
            speed: 15,
            trajectoryType: TrajectoryType.Parabola,
        },
    ],
};

export const STAGE_WAVES_DATA: [string, number, number][][][] = [
    // stage 00
    [
        // wave 1
        [
            ["s", 0, 0],
            ["s", 1, 1],
            ["s", 2, 1],
            ["s", 3, 1],
            ["s", 4, 1],
            ["s", 5, 1],
            ["s", 6, 0],
            ["s", 7, 1],
            ["s", 8, 1],
            ["s", 9, 0],
            ["s", 10, 1],
            ["s", 12, 0],
            ["s", 14, 1],
            ["s", 16, 0],
        ],
        // wave 2
        [
            ["r", 0, 0],
            ["s", 1, 0],
            ["r", 4, 0],
            ["s", 5, 0],
            ["s", 8, 0],
            ["r", 9, 0],
            ["s", 11, 0],
            ["s", 12, 0],
            ["s", 13, 0],
            ["r", 14, 0],
        ],
        // wave 3
        [
            ["s", 0, 0],
            ["s", 1, 0],
            ["s", 2, 0],
            ["s", 3, 0],
            ["r", 3, 0],
            ["s", 4, 0],
            ["s", 6, 0],
            ["s", 8, 0],
            ["r", 9, 0],
            ["s", 10, 0],
            ["s", 11, 0],
            ["s", 12, 0],
            ["s", 13, 0],
            ["s", 14, 0],
            ["r", 15, 0],
            ["s", 16, 0],
            ["s", 17, 0],
        ],
        // wave 4
        [
            ["b", 0, 0],
            ["s", 0, 0],
            ["s", 1, 0],
            ["s", 2, 0],
            ["s", 3, 0],
            ["r", 3, 0],
            ["s", 4, 0],
            ["b", 5, 0],
            ["s", 6, 0],
            ["s", 8, 0],
            ["r", 9, 0],
            ["s", 10, 0],
            ["b", 10, 0],
            ["s", 11, 0],
            ["s", 12, 0],
            ["s", 13, 0],
            ["s", 14, 0],
            ["r", 15, 0],
            ["b", 15, 0],
            ["s", 16, 0],
            ["s", 17, 0],
            ["s", 18, 0],
        ],
        // wave 5
        [
            ["b", 0, 0],
            ["s", 0, 0],
            ["s", 1, 0],
            ["s", 2, 0],
            ["w", 2, 0],
            ["s", 3, 0],
            ["r", 3, 0],
            ["s", 4, 0],
            ["b", 5, 0],
            ["s", 6, 0],
            ["w", 7, 0],
            ["s", 8, 0],
            ["r", 9, 0],
            ["s", 10, 0],
            ["b", 10, 0],
            ["s", 11, 0],
            ["s", 12, 0],
            ["s", 13, 0],
            ["w", 13, 0],
            ["s", 14, 0],
            ["r", 15, 0],
            ["b", 15, 0],
            ["s", 16, 0],
            ["s", 17, 0],
            ["s", 18, 0],
            ["w", 19, 0],
            ["s", 19, 0],
            ["s", 20, 0],
            ["r", 20, 0],
            ["s", 21, 0],
            ["w", 21, 0],
            ["s", 22, 0],
            ["s", 23, 0],
            ["s", 24, 0],
        ],
    ],

    // stage 01
    [
        // wave 000
        [
            ...waveSegment(EnemyChar.Warrior, 2.3),
            ...waveSegment(EnemyChar.Soldier, 2.5, 10, 30),
            ...waveSegment(EnemyChar.Brigand, 2.3, 10, 60),
            ...waveSegment(EnemyChar.Spider, 1.5, 100, 0, [-1, 1]),
        ],
        // wave 1
        waveSegment(EnemyChar.Spider),
        // wave 2
        waveSegment(EnemyChar.Brigand, 2),
        // wave 3
        [...waveSegment(EnemyChar.Soldier, 2), ...waveSegment(EnemyChar.Spider)],
        // wave 4
        [...waveSegment(EnemyChar.Warrior, 2), ...waveSegment(EnemyChar.Spider, 0.8, 20)],
        // wave 5
        [
            ...waveSegment(EnemyChar.Brigand, 2),
            ...waveSegment(EnemyChar.Soldier, 2, 10, 22),
            ...waveSegment(EnemyChar.Spider, 0.8, 20),
        ],
        // wave 5
        [
            ...waveSegment(EnemyChar.Brigand, 2),
            ...waveSegment(EnemyChar.Warrior, 2, 10, 22),
            ...waveSegment(EnemyChar.Spider, 0.8, 50),
        ],
        // wave 6
        [
            ...waveSegment(EnemyChar.Warrior, 2),
            ...waveSegment(EnemyChar.Soldier, 2, 10, 22),
            ...waveSegment(EnemyChar.Brigand, 2, 10, 44),
            ...waveSegment(EnemyChar.Spider, 1.5, 100, 0, [-1, 1]),
        ],
    ],

    // stage 02
    [
        // wave 1
        [
            ["s", 0, 0],
            ["s", 2, 0],
            ["s", 4, 0],
            ["s", 6, 0],
        ],
        // wave 2
        [
            ["s", 0, 0],
            ["s", 1, 0],
            ["s", 2, 0],
            ["s", 3, 0],
            ["s", 4, 0],
            ["s", 5, 0],
            ["s", 6, 0],
        ],
        //...
    ],

    // stage 03
    [
        // wave 1
        [
            ["z", 0, 0],
            ["s", 1, 0],
            ["z", 3, 0],
            ["s", 4, 0],
            ["r", 6, 0],
            ["s", 7, 0],
            ["z", 9, 0],
            ["s", 10, 0],
        ],
    ],
    // stage 04
    [
        // wave 1
        [
            ["b", 0, 0],
            ["s", 1, 0],
            ["b", 3, 0],
            ["s", 4, 0],
            ["r", 6, 0],
            ["s", 7, 0],
            ["b", 9, 0],
            ["s", 10, 0],
        ],
    ],
    // stage 05
    [
        // wave 1
        [
            ["w", 0, 0],
            ["s", 1, 0],
            ["w", 3, 0],
            ["s", 4, 0],
            ["r", 6, 0],
            ["s", 7, 0],
            ["w", 9, 0],
            ["s", 10, 0],
        ],
    ],
];

function waveSegment(
    e: EnemyChar,
    interval = 1,
    enemyCount = 10,
    startSpawningAt = 0,
    xOffList = [0]
): [EnemyChar, number, number][] {
    // console.log("waveSegment", { e, enemyCount, interval, startSpawningAt, xOffList });

    return Array.from({ length: enemyCount }, (_, index) => [
        e,
        index * interval + startSpawningAt,
        xOffList[index % xOffList.length],
    ]);
}

//   // Wave 1

//   // Wave 2
//   Array.from({ length: 10 }, (_, index) => [EnemyChar.Spider, index * 2, 0]),

//   // Wave 3
//   Array.from({ length: 18 }, (_, index) => [EnemyChar.Warrior, index * 1.5, 0]),

//   // Wave 4
//   Array.from({ length: 26 }, (_, index) => [EnemyChar.Orc, index * 1, 0]),

//   // Wave 5
//   Array.from({ length: 35 }, (_, index) => [EnemyChar.Brigand, index * 1, 0]),

//   // Wave 6
//   Array.from({ length: 45 }, (_, index) => [EnemyChar.Soldier, index * 1, 0]),

//   // Wave 7
//   Array.from({ length: 56 }, (_, index) => [EnemyChar.Spider, index * 1, 0]),
